spring.application.name=rednote-file-microservice
server.port=9010

# 文件上传配置
file.upload-dir=/data/rednote
file.static-path-prefix=/uploads/

# 上传文件大小限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 配置内嵌的 tomcat 的最大吞吐量
server.tomcat.max-swallow-size = 100MB

# 配置 MongoDB
#spring.data.mongodb.uri=mongodb://admin:admin123@192.168.68.157:27017
spring.data.mongodb.grid-fs-database=rednote_files
spring.data.mongodb.host=192.168.68.157
spring.data.mongodb.port=27017
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin123
spring.data.mongodb.database=rednote
spring.data.mongodb.authentication-database=rednote

# 配置 JWT
## 你的Base64编码密钥（至少256位）
app.jwtSecret=bQUBj9U7io0VXuhlaC9XmeaSGSwkqOlG4itHzIgUvOk=
## 24小时
app.jwtExpirationMs=86400000

# 配置 Spring Cloud Loadbalancer
spring.cloud.loadbalancer.enabled=true

# 配置 Nacos
spring.cloud.loadbalancer.nacos.enabled=true
spring.cloud.nacos.discovery.server-addr=192.168.68.157:8280
management.endpoints.web.exposure.include=*
spring.cloud.nacos.config.server-addr=192.168.68.157:8280
spring.config.import[0]=nacos:rednote-file-microservice.properties?group=DEFAULT_GROUP

# 配置 Seata
seata.tx-service-group=rednote_tx_group
seata.service.vgroup-mapping.rednote_tx_group=default
seata.registry.type=nacos
seata.registry.nacos.server-addr=192.168.68.157:8280
seata.registry.nacos.namespace=public
seata.registry.nacos.cluster=default