spring.application.name=rednote-ai-microservice
server.port=9050

# 配置 JWT
## 你的Base64编码密钥（至少256位）
app.jwtSecret=bQUBj9U7io0VXuhlaC9XmeaSGSwkqOlG4itHzIgUvOk=
## 24小时
app.jwtExpirationMs=86400000

# 配置 Spring Cloud Loadbalancer
spring.cloud.loadbalancer.enabled=true

# 配置 Nacos
spring.cloud.loadbalancer.nacos.enabled=true
spring.cloud.nacos.discovery.server-addr=192.168.68.157:8280
management.endpoints.web.exposure.include=*
spring.cloud.nacos.config.server-addr=192.168.68.157:8280
spring.config.import[0]=nacos:rednote-ai-microservice.properties?group=DEFAULT_GROUP

# 配置 Seata
seata.tx-service-group=rednote_tx_group
seata.service.vgroup-mapping.rednote_tx_group=default
seata.registry.type=nacos
seata.registry.nacos.server-addr=192.168.68.157:8280
seata.registry.nacos.namespace=public
seata.registry.nacos.cluster=default

# Spring AI配置
spring.ai.dashscope.api-key=${SPRING_AI_DASHSCOPE_API_KEY}
logging.level.org.springframework.ai=debug
logging.level.com.alibaba.dashscope.api=debug
logging.level.com.alibaba.cloud.ai.dashscope.chat=debug