# 定义部署Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rednote-admin-microservice
  namespace: rednote
  labels:
    app: rednote-admin
spec:
  replicas: 1 # 副本数
  selector:
    matchLabels:
      app: rednote-admin
  strategy:
    type: RollingUpdate # 滚动更新
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rednote-admin
    spec:
      containers:
        - name: rednote-admin-microservice
          image: rednote-admin-microservice:1.0.0
          imagePullPolicy: Never  # 使用本地镜像
          ports:
            - containerPort: 9040
              protocol: TCP
          # 资源限制
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi  
          # 环境变量
          env:
            - name: spring.cloud.nacos.discovery.server-addr
              value: host.docker.internal:8280
            - name: spring.cloud.nacos.config.server-addr
              value: host.docker.internal:8280  
            - name: seata.registry.nacos.server-addr
              value: host.docker.internal:8280    
            - name: spring.data.redis.host
              value: host.docker.internal
            - name: spring.kafka.bootstrap-servers
              value: host.docker.internal:9092    
---
# 定义服务Service
apiVersion: v1
kind: Service
metadata:
  name: rednote-admin-microservice
  namespace: rednote
spec:
  type: ClusterIP # 集群内访问
  selector:
    app: rednote-admin
  ports:
    - port: 9040
      targetPort: 9040
      protocol: TCP